server:
  port: 8191
spring:
  application:
    name: api-gateway-server-ms
  cloud: 
    gateway:
      discovery: 
        locator: 
          enabled: true
          lowerCaseServiceId: true
      routes:      - id: currency-exchange-service
        uri: lb://currency-exchange-service
        predicates: 
        - path=/currency-exchange-api/**
        filters:         - name: CircuitBreaker
           args:
            name: currency-exchange-service
            fallbackuri: forword:/currency-exchange-service-fallback
      - id: currency-conversion-service
        uri: lb://currency-conversion-service
        predicates: 
        - path=/currency-conversion-api/**
        filters:
         - name: CircuitBreaker
           args:
            name: currency-conversion-service
            fallbackuri: forword:/currency-conversion-service-fallback
management:  endpoints:    web:      exposure:        include:        - '*'
hystrix:
 command:
  fallbackcmd:
   execution:
    isolation:
     thread:
      timeOutInMilliSeconds: 4000